// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apftypegzfzqmmzthccj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwZnR5cGVnemZ6cW1tenRoY2NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NDc3MzksImV4cCI6MjA2OTAyMzczOX0.ux2dk03-V39jCg-uJYxnW-Mw6Tvmeyfl-rgna22NVPI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});